# FUNCOES:
# -> CRUD FOTOS PARA A MEMÓRIA
# -> FUNCAO PARA ACRESCENTAR ESTILO NO PDF
# -> JUNTAR FOTOS DA MEMÓRIA PARA O PDF
# -> FUNCAO PARA COLETAR DADOS DO EQUIPAMENTO
# -> 

import images.CRUD as CRUD

IMAGE_LIST = []


CRUD.upload_Images(input(),IMAGE_LIST)

print(IMAGE_LIST)



