# Generated by Django 6.1 on 2026-09-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_checklist_title_alter_imagenschecklist_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='tipo',
            new_name='type',
        ),
    ]
